// SPDX-FileCopyrightText: 2022 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2024 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client.Stylesheets;
using Content.Shared.Speech;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.VoiceMask;

[GenerateTypedNameReferences]
public sealed partial class VoiceMaskNameChangeWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public Action<string>? OnNameChange;
    public Action<string?>? OnVerbChange;
    public Action<ProtoId<JobIconPrototype>>? OnJobIconChanged;

    private const int JobIconColumnCount = 10;

    private readonly SpriteSystem _spriteSystem;

    private List<(string, string)> _verbs = new();
    private List<ProtoId<JobIconPrototype>> _jobIcons = new();
    private Dictionary<ProtoId<JobIconPrototype>, Button> _jobIconButtons = new();
    private ButtonGroup? _jobIconButtonGroup = new();

    private string? _verb;
    private ProtoId<JobIconPrototype>? _currentJobIcon;

    public VoiceMaskNameChangeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };
    }

    public void ReloadVerbs(IPrototypeManager proto)
    {
        foreach (var verb in proto.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    public void ReloadJobIcons(IPrototypeManager proto)
    {
        var icons = proto.EnumeratePrototypes<JobIconPrototype>()
            .Where(icon => icon.AllowSelection)
            .ToList();

        icons.Sort((x, y) => string.Compare(x.LocalizedJobName, y.LocalizedJobName, StringComparison.CurrentCulture));
        _jobIcons = icons.Select(icon => (ProtoId<JobIconPrototype>) icon.ID).ToList();
    }

    public void AddJobIcons()
    {
        IconGrid.DisposeAllChildren();
        _jobIconButtons.Clear();

        for (var i = 0; i < _jobIcons.Count; i++)
        {
            var jobIcon = _prototype.Index(_jobIcons[i]);

            var styleBase = StyleClass.ButtonOpenBoth;
            var mod = i % JobIconColumnCount;

            if (mod == 0)
                styleBase = StyleClass.ButtonOpenRight;
            else if (mod == JobIconColumnCount - 1)
                styleBase = StyleClass.ButtonOpenLeft;

            var button = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = _jobIconButtonGroup,
                Pressed = jobIcon.ID == _currentJobIcon,
                ToolTip = jobIcon.LocalizedJobName,
            };

            button.AddChild(new TextureRect
            {
                Texture = _spriteSystem.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            });

            _jobIconButtons.Add(jobIcon.ID, button);

            button.OnPressed += _ =>
            {
                _currentJobIcon = jobIcon.ID;
                OnJobIconChanged?.Invoke(jobIcon.ID);
            };

            IconGrid.AddChild(button);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is {} metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

    public void UpdateState(string name, string? verb, ProtoId<JobIconPrototype>? jobIcon)
    {
        NameSelector.Text = name;
        _verb = verb;
        _currentJobIcon = jobIcon;

        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (string.Equals(verb, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }

        if (jobIcon is not { } protoId)
        {
            if (_jobIconButtonGroup?.Pressed is { } pressedButton)
                pressedButton.Pressed = false;

            return;
        }

        if (_jobIconButtons.TryGetValue(protoId, out var button))
            button.Pressed = true;
    }
}
