// SPDX-License-Identifier: MIT

using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(LogProbeUiState state)
    {
        ProbedDeviceContainer.RemoveAllChildren();
        TitleLabel.Text = Loc.GetString("log-probe-header-access");
        ContentLabel.Text = Loc.GetString("log-probe-label-accessor");
        CardNumberLabel.Visible = false;

        if (state.PulledLogs.Count > 0)
            DisplayAccessLogs(state.PulledLogs);
    }

    private void DisplayAccessLogs(List<PulledAccessLog> logs)
    {
        logs.Reverse();
        var count = 1;
        foreach (var log in logs)
        {
            var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
            var entry = new LogProbeUiEntry(count, timeLabelText, log.Accessor);
            ProbedDeviceContainer.AddChild(entry);
            count++;
        }
    }
}
